# Generated by Django 2.1.7 on 2021-05-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='placed_by',
        ),
        migrations.DeleteModel(
            name='AddressDetails',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
